services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - mysql
    environment:
      DATABASE_TYPE: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USERNAME: ${DATABASE_USERNAME}      
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}      
      DATABASE_NAME: ${DATABASE_NAME}         
      SYNCHRONIZE: false
      AUTHENTICATION_KEY: ${AUTHENTICATION_KEY}
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run start

volumes:
  mysql_data: